### ISSUE TITLE
user-friendly chunking of service calls?

### ISSUE THREAD

**Issue by jordansread** [DOI-USGS/dataRetrieval#185]
In order to make it more common for supporting smaller, more manageable queries and then aggregating them on the client side, I wonder if it is within scope to support a few chunking options in WQP calls, such as time or space. An example of this would be:

``` r
readWQPdata(statecode="US:MN", siteType="Lake, Reservoir, Impoundment", 
    characteristicName=charName, startDateLo='01-01-1990', startDateHi='12-31-2010', timeChunk='5y')
```

Not sure about the syntax, but a way to have an individual aggregate call that is too big automatically handled by a chunking feature within dataRet. So this particular example would call `readWQPdata` 5 times using intervals of 5 years to set `startDateHi` and `startDateLo` values, and then bind them and return the full result to the user.

**Comment by ldecicco-USGS** [comment]
Would this be better as a blog example?

**Comment by jread-usgs** [comment]
maybe?

**Comment by ldecicco-USGS** [comment]
On second thought....you could use the header response to decide if splitting up the calls would make sense. Especially WQP

**Comment by jread-usgs** [comment]
agreed. My thoughts are that you need maybe a bit too much insider knowledge to use the WQP service calls right now.

**Comment by ldecicco-USGS** [comment]
Revisit after POST + sampling activity work to see if still necessary.

**Comment by ldecicco-USGS** [comment]
Ask WQP team if there's an optimal way to do things.
