### ISSUE TITLE
expose a setter for package variables

### ISSUE THREAD

**Issue by jordansread** [DOI-USGS/dataRetrieval#394]
https://github.com/USGS-R/dataRetrieval/blob/4513780d167cea137ebec3702bc731704ad6c2da/R/setAccess.R#L43

ability to set these env variables. would be useful for testing, or if the service URLs change

**Comment by wdwatkins** [comment]
follow the geoknife pattern? https://github.com/USGS-R/geoknife/blob/b3bec33226e4a4516fcc5ef5cb67660122d2bb34/R/00-gconfig.R

**Comment by ldecicco-USGS** [comment]
yeah, that looks good

**Comment by jordansread** [comment]
PS, was chatting with Eric E who mentioned this

> Oh, I'm not sure why they errors, but I see the confusion: you are using a legacy form of the prod urls. All services are cannonically available at https://www.waterqualitydata.us/data.

> We have some special additional url mappings to handle people who still use the old url form, which omits the '/data' portion for Result, Station and Activity. Not for ActivityMetric, however - that url must be handled by the UI.


When I shared the current pkg.env data:
```r

  pkg.env$wqpData = "https://www.waterqualitydata.us/Result/search"
  pkg.env$wqpStation = "https://www.waterqualitydata.us/Station/search"
  pkg.env$wqpActivity = "https://www.waterqualitydata.us/Activity/search"
  pkg.env$wqpMetrics = "https://www.waterqualitydata.us/ActivityMetric/search"
```
