### ISSUE TITLE
readWQPsummary updates

### ISSUE THREAD

**Issue by ldecicco-USGS** [DOI-USGS/dataRetrieval#613]
1. The WQP summary service doesn't seem to accept the start/end dates. We should either give user a warning that the dates aren't included in the query OR do the data filtering on our own. Another suggestion might be to as if WQP wants to implement it.
2. If users somehow notice from the WQP site itself that all summary queries have the dataProfile="periodofrecord", then I think we need to check that we're not double specifying it in the URL.

**Comment by lstanish-usgs** [comment]
In response to the items noted here:
1. start/end dates are currently not allowed parameters for the WQP summary service. This could be implemented in a future version of the summary service. 
2. 'periodofrecord' is the most common dataProfile queried by the summary service, however there is also 'summaryMonitoringLocation', which is actually the default dataProfile. If no dataProfile is specified, the service will return data in the 'summaryMonitoringLocation' format.
- Some of the confusion with the summary service should be alleviated when the revised documentation is published on the WQP site, which should be soon!

**Comment by ldecicco-USGS** [comment]
But `summaryMonitoringLocation` is only with geojson so we'll need to adjust the code for that unique format relative to dataRetrieval.

**Comment by ldecicco-USGS** [comment]
And also if any current `dataRetrieval` user is reading this.... _at the moment_, in `dataRetrieval`, if no dataProfile is specified in the `readWQPsummary` function, then `dataRetrieval` adds dataProfile="periodofrecord". When we were developing this function, there wasn't actually any dataProfile=summaryMonitoringLocation output to test. The summaryMonitoringLocation profile will need some work to get it incorporated in `dataRetrieval`.
