### ISSUE TITLE
Review of dataRetrieval v2.7.11

### ISSUE THREAD

**Issue by elbeejay** [DOI-USGS/dataRetrieval#642]
Title: "Review of dataRetrieval v2.7.11"
---
Checklist is a combination of the rOpenSci [Review template](https://devguide.ropensci.org/reviewtemplate.html#reviewtemplate) and JOSS [Review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html).

This review is focused on the changes made to the package between v2.7.7 and v2.7.11 (the second-latest and latest released on GitHub respectively).

#### General checks

- [x] **Repository:** Is the source code for this software available at [https://github.com/USGS-R/dataRetrieval](https://github.com/USGS-R/dataRetrieval)?
- [x] **License:** Does the repository contain a plain-text LICENSE file?
- [x] **Contribution and authorship:** Has the submitting author made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions
- [x] **Examples:** (that run successfully locally) for all exported functions. Do the authors include examples of how to use the software (ideally to solve real-world analysis problems)?
- [x] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`). Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support?

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [x] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine. Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

---

### Review Comments

I found the functionality and documentation associated with `whatWQPdata()`, `readWQPdata()` and `whatNWISdata()` to be clear and easy to read. The functions work as described, and the documentation contains multiple examples showcasing some of the different features of each individual function.

Some more general minor comments are the following:

- Additional community guidelines should be added to make it clear to potential contributors how they should go about contributing to the project. For new features should a new issue be opened first? What are guidelines on tests, documentation and code style? Is development done via direct branching or a fork and branch workflow? 
- Somewhat related to above, feature branch `Issue610` can be deleted as it has been merged into `main`. Should developers work on branches in the main repository or on branches of their forks?
- The Twitter button text should be revised to say "Follow USGS_DataSci" as that is where it directs you when clicked

Some of these things may seem obvious, but I think the `README.md` file should explicitly describe:
- What/where vignettes are and how to run/generate them
- How to do a "developer" installation of the package, and general guidelines on how to be a developer/contributor
- How to run the automated tests

__Note:__ Comments are being addressed in https://code.usgs.gov/water/dataRetrieval/-/merge_requests/432

**Comment by ldecicco-USGS** [comment]
Here's version 1 of How to Contribute:
https://rconnect.usgs.gov/dataRetrieval/articles/Contributing.html
I'm hoping we take our time to refine this over time.
