### ISSUE TITLE
Can't query data using the dataRetrieval functions

### ISSUE THREAD

**Issue by aachmano** [DOI-USGS/dataRetrieval#647]
**What is your question?**
Hello, I am new to using the dataRetrieval package but I can't seem to get it working.

**To Reproduce**
I started by using the code posted on the help/vignette 

```r
library(dataRetrieval)
site <- "USGS.430427089284901"
site_info <- readNGWMNsites(siteNumbers=site)
```

**Expected behavior**
I expected it to retrieve the site info for the given site number

**Screenshots**
However, I keep getting the following error. something to do with my attr()?
![image](https://user-images.githubusercontent.com/116903643/200060113-491fe43c-6460-4b1f-a7ff-37c8958003be.png)

OR here is the error in written format

"DISCLAIMER: NGWMN retrieval functions are still in flux, 
              and no future behavior or output is guaranteed
Unknown content, returning NULL
Error in attr(siteDF, "url") <- url : attempt to set an attribute on NULL

Can anyone please help?

**Comment by ldecicco-USGS** [comment]
Sorry @aachmano!
The services are currently down due to some databases work. I was told to expect them back up and running sometime next week. I'll let you know when I hear they are back up.

**Comment by aachmano** [comment]
@ldecicco-USGS Thank you so much for you timely response, I really appreciate it! I will be on the lookout for your green light next week.

**Comment by hallieella** [comment]
Hello @ldecicco-USGS! I was having a similar issue, are the databases up and running again? Thank you!

**Comment by ldecicco-USGS** [comment]
Some of the database issues have been resolved...some are still being fixed. I think if you are asking for `service = "observation"`, things are mostly working. The `service="featureOfInterest"` is still not working properly. 

My understanding is that the developers are getting close to having it all straightened out!

**Comment by hallieella** [comment]
Good to know, thank you!

**Comment by ldecicco-USGS** [comment]
I believe the featureOfInterest services are also now working. If you notice any problems, let me know.
