### ISSUE TITLE
Web services status

### ISSUE THREAD

**Issue by mishmishalmish** [DOI-USGS/dataRetrieval#663]
Hello, I am having trouble accessing the web services for EPA's WQP.  Is there a status site where I can find out if it is just me or if the web service is down? I am trying to access the web services for STORET/WQX. Thanks!

**Comment by ldecicco-USGS** [comment]
I think things have been pretty stable for 2 days. Give it another try and let me know if anything gives you problems.

**Comment by mishmishalmish** [comment]
Thank you, it's working for me.
