### ISSUE TITLE
readNWISsite

### ISSUE THREAD

**Issue by fhmejia** [DOI-USGS/dataRetrieval#675]
**What is your question?**
I am using the readNWISsite function, but I keep getting this error: 

Error in (function (file, delim, quote = "\"", escape_backslash = FALSE,  : 
  unused argument (show_col_types = FALSE)

My code is the following:
siteinfo<- readNWISsite(c("14144800","14144900","14145500","14147500","14148000"))

I am hoping to use this function with 200 sites, but I can't even get a few.  What am I doing wrong?

Thanks!

**Comment by ldecicco-USGS** [comment]
Hmm, that code worked for me. My first suggestion would be to update all your packages, the error message sounds vaguely like it might be coming from the "readr" package. 

The easiest way to update (if you are using RStudio) is to go to the Package tab, and click the Update button. 

![image](https://github.com/DOI-USGS/dataRetrieval/assets/1105215/564c2ca6-73e8-4106-b29f-7d0782ae3007)


If that doesn't solve the problem, could you let me know what you see when you run:

```r
sessionInfo()
```

**Comment by fhmejia** [comment]
Thank you!! updating the readr package solve my problem!!!
