### ISSUE TITLE
Drainage area retrieval from sites

### ISSUE THREAD

**Issue by Katianagr** [DOI-USGS/dataRetrieval#700]
Is there a way to extract the drainage area of multiple stream sites?
 
I extracted all of the Puerto Rico active stream sites using the readNWISdata and this gave me a full list along with their coordinate information. I am trying to see if there is a way to get the drainage area corresponding to each site since there are a lot. This is the code I have so far:
USGS_PR_COORDS <- readNWISdata(stateCd = "pr",
                    siteStatus = "active",
                    siteType = "ST",
                    hasDataTypeCd = "dv",
                    service="site")

**Comment by lstanish-usgs** [comment]
Hello @Katianagr,
There is an argument - called siteOutput - for readNWISdata(). Set that to "expanded" and the function will retrieve drainage areas along with a bunch of other site metadata:
USGS_PR_COORDS <- readNWISdata(stateCd = "pr",
                               siteStatus = "active",
                               siteType = "ST",
                               hasDataTypeCd = "dv",
                               service="site", 
                               siteOutput="expanded")
Hopefully that gets you what you need.
