### ISSUE TITLE
readWQPqw retrieves a mixed table of environmental and QA data-- how to retrieve only environmental sample data

### ISSUE THREAD

**Issue by jmusgs** [DOI-USGS/dataRetrieval#712]
I am in the process of converting some web pages that use readNWISqw to the WQP.  So am I to understand correctly, that with a basic retrieval, you get all sample types including QA data?  Is there any command or option to only get sample data and not QA data in your retrieval.  I think it's problematic that they are all mixed in the same file, just because many users won't check.

```r
library(dataRetrieval)
Cl_sites <- c("01193500", "01208500", "01196500", "01192500")
parameterCd <- "00940"

qwdata <- readWQPqw(paste0("USGS-", Cl_sites), parameterCd)
```

**Expected behavior**
Retrieve only routine sample data (environmental samples only, with no QA data)
**Screenshots**
Note below sample types retrieved
unique(qwdata$Activity_TypeCode)
[1] "Sample - Routine, regular"                            
[2] "Quality Control Sample - Other QC, blind"             
[3] "Sample - Routine, with an associated replicate"       
[4] "Quality Control Sample - Other QC, reference material"

**Comment by lstanish-usgs** [comment]
Hi @jmusgs and thanks for the feedback. At this time we do not have a simple way to filter out QA/QC data prior to downloading the data, which is not a query argument currently available from the web service. Users who have relied on the WQP services are likely familiar with the existence of QA/QC data, however it's a good reminder that there will be new users of the WQP services that may not be aware. For now, we can update our documentation with examples of filtering QA/QC data. We'll investigate the feasibility of adding an argument to filter out QC data after downloading. In the interim, you can filter the QC data out with some additional code, here's one approach:
qwdata_qc_clean <- qwdata[grep("(?i)routine", qwdata$Activity_TypeCode), ]

**Comment by ldecicco-USGS** [comment]
For the record, the NWIS qw records also contained that data:

```r
qwdata_nwis <- readNWISqw(Cl_sites, parameterCd)
unique(qwdata_nwis$samp_type_cd)
[1] "9" "7" "5" "6" "4"
```
Those codes relate to:
https://help.waterdata.usgs.gov/sample_type

9 = Regular
7 = Replicate
5 = Duplicate
6 = Reference
4 = Blind

I know for most of my analyses, I almost always started the work by filtering to samp_type_cd == 9, so now I'll be switching to Activity_TypeCode == "Sample - Routine, regular"

**Comment by jmusgs** [comment]
Thanks for your comments on it.  As it turns out, these are samples that were coded to the wrong database and will need to be fixed.  We shouldn't be able to pull any QA/QC data from public databases just yet, so theoretically all retrievals should only include regular sample types.  These are samples that were either miscoded as QA/QC samples or placed in the wrong database.

**Comment by lstanish-usgs** [comment]
I've heard from other science centers who intentionally publish at least some QC data, but that does vary across science centers. It is a good point that many users may not be aware that QC data are present and therefore are not checking their data, which is a problem. 
As far as dataRetrieval updates, we will add a QC filtering step to the WQP tutorial, but will leave it up to users to perform that step. If at some time in the future the services add functionality to filter QC data, we would definitely be able to add that to the dataRetrieval functions.
